@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Matheus Martins",
  "email": "matheus@teste.com.br",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "matheus2@teste.com.br",
  "password": "12345678"
}

###

# @name get_profile
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_goal
POST {{baseUrl}}/goals
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Testeeee",
  "description": "",
  "budget": 3200,
  "deadline": "10/10/2024",
  "imageUrl": ""
}

###

# @name delete_goal
DELETE {{baseUrl}}/goals/7e390f36-5043-4ad7-b1dc-bad6f8cc086d
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_user_goals
GET {{baseUrl}}/goals
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_goal
PUT {{baseUrl}}/goals/0b9c5992-5a47-42e0-8036-f871e9d57497
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "completed": false
}

###

# @name create_objective
POST {{baseUrl}}/objectives
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "goalId": "0b9c5992-5a47-42e0-8036-f871e9d57497",
  "title": "Objetivo 3",
  "expense": 4200
}

###

# @name get_goals_objectives
GET {{baseUrl}}/objectives/0b9c5992-5a47-42e0-8036-f871e9d57497
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_objective
PUT {{baseUrl}}/objectives/d9c71704-42b8-4415-96c3-51d8c5166341
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "description": "Teste"
}

###

# @name delete_objective
DELETE {{baseUrl}}/objectives/2f2c9a38-eccf-4990-9b8e-3021acfe898e
Content-Type: application/json
Authorization: Bearer {{authToken}}
