@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Matheus Martins",
  "email": "matheus@teste.com.br",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "matheus2@teste.com.br",
  "password": "12345678"
}

###

# @name get_profile
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_goal
POST {{baseUrl}}/goals
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Teste de Meta",
  "description": "",
  "budget": 3200,
  "deadline": "10/10/2024",
  "imageUrl": ""
}

###

# @name delete_goal
DELETE {{baseUrl}}/goals/27ce5ce6-fc7c-455f-a7dc-23cf0c70f448
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_user_goals
GET {{baseUrl}}/goals
Content-Type: application/json
Authorization: Bearer {{authToken}}
