version: '3.8'

services:
  postgres:
    container_name: database-trowel
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trowel123
      POSTGRES_DB: trowel
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
